version: '2'

services:
  db:
    build: .
    image: amana-mssql2017:1.0.0
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 2astazeY
      MSSQL_DB: flyway
      MSSQL_USER: flyway
      MSSQL_PASSWORD: flyway2018#
    ports:
       - "1433:1433"
    container_name: mssql2017